set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(MINGW_C_COMPILER x86_64-w64-mingw32-gcc)
if(NOT MINGW_C_COMPILER)
    message(FATAL_ERROR "x86_64-w64-mingw32-gcc not found in PATH")
endif()
set(CMAKE_C_COMPILER "${MINGW_C_COMPILER}")

find_program(MINGW_RC_COMPILER x86_64-w64-mingw32-windres)
if(MINGW_RC_COMPILER)
    set(CMAKE_RC_COMPILER "${MINGW_RC_COMPILER}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
