#!/usr/bin/env python3
"""Deterministic disassembly workflow for extracted NK flat images."""

import argparse
import pathlib
import re
import subprocess
import sys
from typing import Dict, List, Tuple


def parse_meta(path: pathlib.Path) -> Dict[str, str]:
    meta: Dict[str, str] = {}
    for raw in path.read_text(encoding="ascii").splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        if "=" not in raw:
            continue
        k, v = raw.split("=", 1)
        meta[k.strip()] = v.strip()
    return meta


def parse_int(value: str) -> int:
    return int(value, 0)


def run_objdump(objdump: str, flat_path: pathlib.Path, base_va: int,
                start: int = None, stop: int = None) -> str:
    cmd = [
        objdump,
        "-D",
        "-b", "binary",
        "-m", "mips:3000",
        "-EL",
        f"--adjust-vma=0x{base_va:X}",
    ]
    if start is not None:
        cmd.append(f"--start-address=0x{start:X}")
    if stop is not None:
        cmd.append(f"--stop-address=0x{stop:X}")
    cmd.append(str(flat_path))

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"objdump failed ({proc.returncode})\n"
            f"cmd: {' '.join(cmd)}\n{proc.stderr}"
        )
    return proc.stdout


LINE_RE = re.compile(r"^\s*([0-9a-fA-F]+):\s+([0-9a-fA-F]{8})\s+([A-Za-z0-9_.]+)\s*(.*)$")
HEX_RE = re.compile(r"\b([0-9A-Fa-f]{8})\b")


def parse_insns(disasm: str) -> List[Tuple[int, str, str, str]]:
    insns: List[Tuple[int, str, str, str]] = []
    for ln in disasm.splitlines():
        m = LINE_RE.match(ln)
        if not m:
            continue
        pc = int(m.group(1), 16)
        word = m.group(2)
        mnem = m.group(3)
        ops = m.group(4).strip()
        insns.append((pc, word, mnem, ops))
    return insns


def find_jal_targets(insns: List[Tuple[int, str, str, str]]) -> List[int]:
    targets = set()
    for pc, _word, mnem, ops in insns:
        if mnem != "jal":
            continue
        hm = HEX_RE.search(ops)
        if hm:
            targets.add(int(hm.group(1), 16))
    return sorted(targets)


def write_ctx_map(path: pathlib.Path,
                  ctx_insns: List[Tuple[int, str, str, str]],
                  targets: List[int]) -> None:
    branch_mnems = {
        "beq", "bne", "beqz", "bnez", "blez", "bgtz",
        "bltz", "bgez", "bltzal", "bgezal", "beql", "bnel",
    }
    mem_mnems = {
        "lb", "lbu", "lh", "lhu", "lw", "lwl", "lwr", "ld",
        "sb", "sh", "sw", "swl", "swr", "sd",
    }

    out: List[str] = []
    out.append("# NK Context Path Map")
    out.append("# This file is generated by tools/disasm_nk_ctx.py")
    out.append("")

    out.append("## Calls")
    any_calls = False
    for pc, _word, mnem, ops in ctx_insns:
        if mnem not in {"jal", "jalr", "bal", "bgezal", "bltzal"}:
            continue
        any_calls = True
        out.append(f"0x{pc:08X}\t{mnem}\t{ops}")
    if not any_calls:
        out.append("(none)")
    out.append("")

    out.append("## Branches")
    any_br = False
    for pc, _word, mnem, ops in ctx_insns:
        if mnem not in branch_mnems:
            continue
        any_br = True
        out.append(f"0x{pc:08X}\t{mnem}\t{ops}")
    if not any_br:
        out.append("(none)")
    out.append("")

    out.append("## Memory Operands")
    any_mem = False
    for pc, _word, mnem, ops in ctx_insns:
        if mnem not in mem_mnems:
            continue
        if "(" not in ops or ")" not in ops:
            continue
        any_mem = True
        out.append(f"0x{pc:08X}\t{mnem}\t{ops}")
    if not any_mem:
        out.append("(none)")
    out.append("")

    out.append("## Direct Call Targets")
    if targets:
        for t in targets:
            out.append(f"0x{t:08X}")
    else:
        out.append("(none)")

    path.write_text("\n".join(out) + "\n", encoding="ascii")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in-dir", required=True,
                    help="Directory containing nk_flat.bin and nk_meta.txt")
    ap.add_argument("--objdump", default="mipsel-linux-gnu-objdump",
                    help="Objdump binary to use (default: mipsel-linux-gnu-objdump)")
    ap.add_argument("--ctx-start", type=parse_int, default=0x80079640,
                    help="Context window start VA (default: 0x80079640)")
    ap.add_argument("--ctx-stop", type=parse_int, default=0x800798A0,
                    help="Context window stop VA (default: 0x800798A0)")
    args = ap.parse_args()

    in_dir = pathlib.Path(args.in_dir)
    flat = in_dir / "nk_flat.bin"
    meta_path = in_dir / "nk_meta.txt"

    if not flat.is_file() or not meta_path.is_file():
        print("error: input dir must contain nk_flat.bin and nk_meta.txt", file=sys.stderr)
        return 2

    meta = parse_meta(meta_path)
    if "base_va" not in meta or "flat_size" not in meta:
        print("error: nk_meta.txt missing base_va/flat_size", file=sys.stderr)
        return 2

    base_va = parse_int(meta["base_va"])
    flat_size = parse_int(meta["flat_size"])
    max_va = base_va + flat_size

    full_dis = run_objdump(args.objdump, flat, base_va)
    (in_dir / "nk_full.disasm.txt").write_text(full_dis, encoding="ascii")

    ctx_dis = run_objdump(args.objdump, flat, base_va,
                          start=args.ctx_start, stop=args.ctx_stop)
    (in_dir / "nk_ctx_window.disasm.txt").write_text(ctx_dis, encoding="ascii")

    ctx_insns = parse_insns(ctx_dis)
    targets = find_jal_targets(ctx_insns)

    for t in targets:
        start = max(base_va, t - 0x20)
        stop = min(max_va, t + 0xA0)
        if start >= stop:
            continue
        target_dis = run_objdump(args.objdump, flat, base_va, start=start, stop=stop)
        (in_dir / f"nk_ctx_target_0x{t:08X}.disasm.txt").write_text(
            target_dis, encoding="ascii"
        )

    write_ctx_map(in_dir / "nk_ctx_map.txt", ctx_insns, targets)

    print(
        "[disasm_nk_ctx]"
        f" base=0x{base_va:08X}"
        f" flat_size=0x{flat_size:X}"
        f" ctx=0x{args.ctx_start:08X}-0x{args.ctx_stop:08X}"
        f" targets={len(targets)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
