#!/usr/bin/env python3
import re
import sys
import zlib
from pathlib import Path


REGION_RE = re.compile(
    r'^\[REGION\] phase=(?P<phase>\w+) name=(?P<name>\S+) '
    r'PA=0x(?P<pa>[0-9A-Fa-f]+) size=0x(?P<size>[0-9A-Fa-f]+) '
    r'status=(?P<status>\w+) crc32=0x(?P<crc>[0-9A-Fa-f]+)'
)

RAW_RE = re.compile(
    r'^\[REGION_RAW\] phase=(?P<phase>\w+) name=(?P<name>\S+) '
    r'PA=0x(?P<pa>[0-9A-Fa-f]+) off=0x(?P<off>[0-9A-Fa-f]+) '
    r'size=0x(?P<size>[0-9A-Fa-f]+) data=(?P<data>[0-9A-Fa-f]+)'
)


def sanitize(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch.lower())
        else:
            out.append("_")
    return "".join(out)


def parse_boot_log(path: Path):
    regions = {}
    raw_chunks = {}

    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        m = REGION_RE.match(line)
        if m and m.group("phase") == "init" and m.group("status") == "OK":
            name = m.group("name")
            regions[name] = {
                "name": name,
                "pa": int(m.group("pa"), 16),
                "size": int(m.group("size"), 16),
                "crc32": int(m.group("crc"), 16),
            }
            continue

        m = RAW_RE.match(line)
        if m and m.group("phase") == "init":
            name = m.group("name")
            raw_chunks.setdefault(name, []).append(
                {
                    "pa": int(m.group("pa"), 16),
                    "off": int(m.group("off"), 16),
                    "size": int(m.group("size"), 16),
                    "data": bytes.fromhex(m.group("data")),
                }
            )

    extracted = []
    for name, meta in sorted(regions.items(), key=lambda item: item[1]["pa"]):
        chunks = sorted(raw_chunks.get(name, []), key=lambda item: item["off"])
        if not chunks:
            continue

        buf = bytearray(meta["size"])
        seen = bytearray(meta["size"])
        for chunk in chunks:
            if chunk["pa"] != meta["pa"]:
                raise SystemExit(f"{name}: inconsistent base PA in REGION_RAW")
            if len(chunk["data"]) != chunk["size"]:
                raise SystemExit(f"{name}: size/data mismatch in REGION_RAW")
            end = chunk["off"] + chunk["size"]
            if end > meta["size"]:
                raise SystemExit(f"{name}: REGION_RAW chunk overruns region")
            buf[chunk["off"]:end] = chunk["data"]
            seen[chunk["off"]:end] = b"\x01" * chunk["size"]

        if any(v == 0 for v in seen):
            raise SystemExit(f"{name}: missing REGION_RAW coverage for one or more bytes")

        crc32 = zlib.crc32(bytes(buf)) & 0xFFFFFFFF
        if crc32 != meta["crc32"]:
            raise SystemExit(
                f"{name}: CRC mismatch boot=0x{meta['crc32']:08X} generated=0x{crc32:08X}"
            )

        extracted.append(
            {
                "name": name,
                "ident": sanitize(name),
                "pa": meta["pa"],
                "size": meta["size"],
                "crc32": crc32,
                "data": bytes(buf),
            }
        )

    return extracted


def emit_header(path: Path, source_path: Path, regions):
    lines = []
    lines.append("/* Auto-generated by tools/extract_wince_hw_seed.py. */")
    lines.append(f"/* Source: {source_path.as_posix()} */")
    lines.append("#pragma once")
    lines.append("")

    for region in regions:
        lines.append(
            f"static const uint8_t wince_hw_seed_{region['ident']}_data[] = {{"
        )
        data = region["data"]
        for idx in range(0, len(data), 12):
            chunk = data[idx:idx + 12]
            payload = ", ".join(f"0x{b:02X}" for b in chunk)
            lines.append(f"    {payload},")
        lines.append("};")
        lines.append("")

    if regions:
        lines.append("static const wince_pa_seed_region_t wince_hw_seed_regions[] = {")
        for region in regions:
            lines.append(
                '    { "%s", UINT32_C(0x%08X), UINT32_C(0x%04X), UINT32_C(0x%08X), '
                "wince_hw_seed_%s_data },"
                % (
                    region["name"],
                    region["pa"],
                    region["size"],
                    region["crc32"],
                    region["ident"],
                )
            )
        lines.append("};")
    else:
        lines.append("static const wince_pa_seed_region_t wince_hw_seed_regions[1] = {")
        lines.append("    { NULL, UINT32_C(0), UINT32_C(0), UINT32_C(0), NULL },")
        lines.append("};")
    lines.append("")
    lines.append(
        f"static const uint32_t wince_hw_seed_region_count = UINT32_C({len(regions)});"
    )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv):
    if len(argv) != 3:
        raise SystemExit(
            "usage: extract_wince_hw_seed.py <BEDiag_boot.txt> <out_header>"
        )

    source = Path(argv[1])
    out_header = Path(argv[2])
    regions = parse_boot_log(source)
    emit_header(out_header, source, regions)
    print(
        f"[extract_wince_hw_seed] wrote {len(regions)} regions to {out_header.as_posix()}"
    )


if __name__ == "__main__":
    main(sys.argv)
