#pragma once

/* Auto-generated by tools/extract_wince_resume_replay.py. */

static const uint32_t wince_resume_replay_sample_count = UINT32_C(25);
static const uint32_t wince_resume_replay_required_support = UINT32_C(10);

static const uint32_t wince_resume_resume_context_22a0_words[] = {
    UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000800),
    UINT32_C(0x01800040), UINT32_C(0x10000000), UINT32_C(0x20000000), UINT32_C(0x00000010),
};
static const uint8_t wince_resume_resume_context_22a0_valid[] = {
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint32_t wince_resume_stack_frame_1770_words[] = {
    UINT32_C(0xBDBDBDBD), UINT32_C(0xFFFFD798), UINT32_C(0xBDBDBDBD), UINT32_C(0xFFFFD7A0),
    UINT32_C(0x00008403), UINT32_C(0x80094E8C), UINT32_C(0x80E64000), UINT32_C(0x80089844),
    UINT32_C(0x00008403), UINT32_C(0x8007A634), UINT32_C(0x00008403), UINT32_C(0x80FB2B74),
    UINT32_C(0x00000001), UINT32_C(0x081AFE0C), UINT32_C(0xFFFFD800), UINT32_C(0x081AFEB0),
    UINT32_C(0x0185F3C0), UINT32_C(0xFFFFFF7F), UINT32_C(0x00000000), UINT32_C(0x8008B52C),
    UINT32_C(0x80E2BFDC), UINT32_C(0x6908B518), UINT32_C(0x80FB221C), UINT32_C(0x80EE906C),
    UINT32_C(0x80E64000), UINT32_C(0x8008B478), UINT32_C(0x00008403), UINT32_C(0x80E64000),
    UINT32_C(0x081AFE0C), UINT32_C(0x081AFE08), UINT32_C(0x1008F1D8), UINT32_C(0x00000000),
    UINT32_C(0x80081500), UINT32_C(0x1008F198), UINT32_C(0x00000000), UINT32_C(0x00000000),
};
static const uint8_t wince_resume_stack_frame_1770_valid[] = {
    0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x00, 0x01,
    0x01, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x01, 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x00,
    0x00, 0x01, 0x01, 0x00, 0x01, 0x01, 0x01, 0x01,
    0x01, 0x01, 0x01, 0x01,
};
static const wince_resume_region_t wince_resume_replay_regions[] = {
    { "resume_context_22a0", UINT32_C(0x000022A0), UINT32_C(0x0020), UINT32_C(8), wince_resume_resume_context_22a0_words, wince_resume_resume_context_22a0_valid },
    { "stack_frame_1770", UINT32_C(0x00001770), UINT32_C(0x0090), UINT32_C(36), wince_resume_stack_frame_1770_words, wince_resume_stack_frame_1770_valid },
};

static const wince_resume_snapshot_t wince_resume_replay_snapshot = {
    UINT32_C(0x000117A8),
    UINT32_C(0x00000000),
    UINT32_C(0x8008B52C),
    wince_resume_replay_regions,
    UINT32_C(2),
    NULL,
    UINT32_C(0),
};
