/* Auto-generated by tools/extract_wince_hw_seed.py. */
/* Source: ce/bediag/BEDiagKick/BEDiag_boot.txt */
#pragma once

static const wince_pa_seed_region_t wince_hw_seed_regions[1] = {
    { NULL, UINT32_C(0), UINT32_C(0), UINT32_C(0), NULL },
};

static const uint32_t wince_hw_seed_region_count = UINT32_C(0);
