# Project: L4BNetLoader
# Makefile created by Dev-C++ 4.9.9.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = l4be.o $(RES)
LINKOBJ  = l4be.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" C:/Dev-Cpp/lib/libwsock32.a  
INCS =  -I"C:/Dev-Cpp/include"  -I"include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include"  -I"include" 
BIN  = server.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before server.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "server.exe" $(LIBS)

l4be.o: l4be.c
	$(CPP) -c l4be.c -o l4be.o $(CXXFLAGS)
